### ISSUE TITLE
6.4 to 6.5

### ISSUE THREAD

**Issue by akronym0** [TuxInvader/focal-mainline-builder#44] opened 2023-09-21 10:31 UTC
Hi,

Thanks for building the mainline kernel!

I added the ppa and my update manager showed a "kernel update 6.5.4". I tried to install, but got only an error message ("could not install the security updates"). Please see also attached screenshot

![image](https://github.com/TuxInvader/focal-mainline-builder/assets/86428317/287e976e-a24f-4c7f-99e9-746266100584)

(Linux Mint 21.2).

**Comment by shinodark** [comment] 2023-09-21 16:23
Hi,

There is indeed a problem with two last builds of 6.5.3 and 6.5.4.
The dependencies were not built, you can confirm that here : https://launchpad.net/~tuxinvader/+archive/ubuntu/jammy-mainline/+build/26721733

It seems there is a problem with rust version during package build... See #43

**Comment by akronym0** [comment] 2023-09-22 04:06
Indeed. Thank you.

> It seems there is a problem with rust version during package build... See #43

**Comment by TuxInvader** [comment] 2023-09-22 07:16
Duplicate of https://github.com/TuxInvader/focal-mainline-builder/issues/43

**Closed as not planned by TuxInvader** 2023-09-22 07:16 UTC
