### ISSUE TITLE
Not more updates for Focal or build issues ?

### ISSUE THREAD

**Issue by Augusto7743** [TuxInvader/focal-mainline-builder#33] opened 2022-12-28 11:34 UTC
Hello.
Only trying understand if will have kernel updates for Focal.

When accessing
https://kernel.ubuntu.com/~kernel-ppa/mainline/v6.1/amd64/
not any kernel compiled deb files.
Canonical is having build issues too ?

However Jammy has build issues with 6.1.
Perhaps not more kernel updates to Focal 20.04 ?

Thanks for reply.
Have an nice week.

**Comment by TuxInvader** [comment] 2022-12-29 16:02
Hi,

If you check [The Ubuntu mainline builds](https://kernel.ubuntu.com/~kernel-ppa/mainline/?C=N;O=D) you'll see that they're all failing to build too. Once they fix their builds, then I'll adjust mine if necessary. But while Ubuntu themselves can't build a kernel, I don't see much mileage in trying to hack it back into life in my little shell script :-)

Cheers :beers:

**Comment by Theelx** [comment] 2023-01-09 15:59
I just built 6.1.4 myself using build.sh and it worked. I think the issue is fixed now.

**Comment by Augusto7743** [comment] 2023-01-09 23:14
For Jammy have an new kernel build.
For Focal have build errors
https://launchpad.net/~tuxinvader/+archive/ubuntu/lts-mainline

**Comment by Theelx** [comment] 2023-01-10 15:56
The error seems to be because the builder is using Python 3.8. I wonder if it can be forced to use Python 3.9+

**Comment by Theelx** [comment] 2023-01-10 16:12
See #34.

**Comment by Augusto7743** [comment] 2023-01-10 22:14
When you try build an new kernel that task will be done in :
- local machine.
or
- launchpad server.
?

**Comment by Augusto7743** [comment] 2023-01-10 22:15
Here have new python for 20.04
sudo add-apt-repository ppa:deadsnakes/ppa

**Comment by TuxInvader** [comment] 2023-01-14 13:33
The focal builds are working again now. I've just published 6.0.19, and 6.1.6 is building.

**Closed as completed by TuxInvader** 2023-01-14 13:33 UTC
